[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "complexplorer"
version = "0.0.1"
authors = [
  { name="Igor Kuvychko", email="igor.kuvychko@gmail.com" },
]
description = "Complex function visualizations inspired by Elias Wegert's 'Visual Complex Functions - An Introduction with Phase Portraits'"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD-3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/kuvychko/complexplorer"
"Bug Tracker" = "https://github.com/kuvychko/complexplorer/issues"
